services:
  anvil:
    image: 851725450525.dkr.ecr.us-east-2.amazonaws.com/anvil:latest
    container_name: anvil
    restart: always
    environment:
      CHAIN_ID: 1337
    ports:
      - "8545:8545"
    volumes:
      - anvil-data:/root/.foundry
  anvil-2:
    image: 851725450525.dkr.ecr.us-east-2.amazonaws.com/anvil:latest
    container_name: anvil2
    restart: always
    environment:
      CHAIN_ID: 1338
    ports:
      - "8546:8545"
    volumes:
      - anvil2-data:/root/.foundry
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: funkybit
      POSTGRES_PASSWORD: funkybit
      POSTGRES_DB: funkybit
      PGUSER: funkybit # is used by psql inside container
    ports:
      - "5432:5432"
  ut_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: funkybit
      POSTGRES_PASSWORD: funkybit
      POSTGRES_DB: funkybit
      PGUSER: funkybit # is used by psql inside container
    ports:
      - "5433:5432"

volumes:
  anvil-data:
  anvil2-data:
