
version: '3.7'

x-environment: &common-arch-environment
  LOG_LEVEL: "debug" # debug, info, error, warn, trace, off
  RUST_BACKTRACE: "1" # enable error stack traces
  NETWORK_MODE: "devnet" # devnet, testnet, mainnet
  PRIVATE_KEY_PASSWORD: "" # Provide a password if you'd like to encrypt the local node keys.
  RPC_BIND_IP: "0.0.0.0" # bind to all IPs
  BITCOIN_RPC_ENDPOINT: "bitcoin" # Replace with your bitcoin node's RPC endpoint
  BITCOIN_RPC_PORT: "18443" # Replace with your bitcoin node's RPC port
  BITCOIN_RPC_USERNAME: "user" # Replace with your bitcoin node's RPC username (if any)
  BITCOIN_RPC_PASSWORD: "password" # Replace with your bitcoin node's RPC password (if any)
  BITCOIN_RPC_WALLET: "testwallet"   # Replace with the name of the wallet to be used by arch-node
  RISC0_DEV_MODE: "1"
  DATA_DIR: "/arch-data"


services:
  zkvm:
    image: ghcr.io/arch-network/zkvm:latest
    platform: linux/amd64
    container_name: zkvm
    restart: always
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      <<: *common-arch-environment
      BOOT_NODE_ENDPOINT: http://127.0.0.1:9001
      ARCH_NODES: http://127.0.0.1:9001,http://arch1:9001,http://arch2:9001
      PROVER_ENDPOINT: http://127.0.0.1:8001
      IS_BOOT_NODE: true
    volumes:
      - ./.arch-data/0:/arch-data

  arch1:
    image: ghcr.io/arch-network/node:latest
    platform: linux/amd64
    container_name: arch1
    restart: always
    ports:
      - "9002:9001"
    environment:
      <<: *common-arch-environment
      BOOT_NODE_ENDPOINT: http://zkvm:9001
      PROVER_ENDPOINT: http://zkvm:8001
    depends_on:
      - zkvm
    volumes:
      - ./.arch-data/1:/arch-data

  arch2:
    image: ghcr.io/arch-network/node:latest
    platform: linux/amd64
    container_name: arch2
    restart: always
    ports:
      - "9003:9001"
    environment:
      <<: *common-arch-environment
      BOOT_NODE_ENDPOINT: http://zkvm:9001
      PROVER_ENDPOINT: http://zkvm:8001
    depends_on:
      - zkvm
    volumes:
      - ./.arch-data/2:/arch-data

  bitcoin:
    image: bitcoin
    platform: linux/amd64
    container_name: bitcoin
    restart: always
    ports:
      - 18443:18443
      - 18444:18444
      - 18445:18445
