environment:
  api:
    DB_HOST: test-db-cluster.cluster-cpwwaa4iqa1s.us-east-2.rds.amazonaws.com
    EVM_CHAINS: anvil,anvil2
    EVM_NETWORK_URL_anvil: http://test-anvil.chainring.co:8545
    EVM_NETWORK_URL_anvil2: http://test-anvil2.chainring.co:8545
    AUTH_TOKEN_VALIDITY_INTERVAL: P1D
    SEQUENCER_HOST_NAME: test-sequencer.chainring.co
    SEQUENCER_PORT: "5337"
    JAVA_TOOL_OPTIONS: "-Xlog:gc+metaspace,gc+heap,gc:stdout:time,tags"
  sequencer:
    QUEUE_HOME: "/data/queues/test"
    CHECKPOINTS_ENABLED: "false"
    SANDBOX_MODE: "true"
    DB_HOST: test-db-cluster.cluster-cpwwaa4iqa1s.us-east-2.rds.amazonaws.com
    JAVA_TOOL_OPTIONS: "-Xlog:gc+metaspace,gc+heap,gc:stdout:time,tags"
  telegrambot:
    DB_HOST: test-db-cluster.cluster-cpwwaa4iqa1s.us-east-2.rds.amazonaws.com
    API_URL: http://test-api.chainring.co:9000
    EVM_CHAINS: anvil,anvil2
    EVM_NETWORK_URL_anvil: http://test-anvil.chainring.co:8545
    EVM_NETWORK_URL_anvil2: http://test-anvil2.chainring.co:8545
    JAVA_TOOL_OPTIONS: "-Xlog:gc+metaspace,gc+heap,gc:stdout:time,tags"
  anvil2:
    CHAIN_ID: "31339"
  otterscan:
    ERIGON_URL: https://test-anvil.chainring.co
  otterscan2:
    ERIGON_URL: https://test-anvil2.chainring.co
services:
  api:
    image: 851725450525.dkr.ecr.us-east-2.amazonaws.com/backend
    count: 1
    is_essential: "true"
    environment: api
    secrets:
      DB_CREDENTIALS: arn:aws:secretsmanager:us-east-2:851725450525:secret:rds!cluster-19a608f6-1f4b-4e6a-849f-27831fcf40de-vkcDz2
  telegrambot:
    image: 851725450525.dkr.ecr.us-east-2.amazonaws.com/telegrambot
    count: 1
    environment: telegrambot
    no_rolling_upgrade: "true"
    secrets:
      DB_CREDENTIALS: arn:aws:secretsmanager:us-east-2:851725450525:secret:rds!cluster-19a608f6-1f4b-4e6a-849f-27831fcf40de-vkcDz2
      TELEGRAM_BOT_TOKEN: arn:aws:secretsmanager:us-east-2:851725450525:secret:test/telegrambot/TELEGRAM_BOT_TOKEN-EJTdMA
  anvil:
    image: 851725450525.dkr.ecr.us-east-2.amazonaws.com/anvil
    count: 1
    is_essential: "true"
  otterscan:
    image: 851725450525.dkr.ecr.us-east-2.amazonaws.com/otterscan
    count: 1
    environment: otterscan
  anvil2:
    image: 851725450525.dkr.ecr.us-east-2.amazonaws.com/anvil
    count: 1
    is_essential: "true"
    environment: anvil2
  otterscan2:
    image: 851725450525.dkr.ecr.us-east-2.amazonaws.com/otterscan
    count: 1
    environment: otterscan2
  sequencer:
    image: 851725450525.dkr.ecr.us-east-2.amazonaws.com/sequencer
    count: 1
    is_essential: "true"
    no_rolling_upgrade: "true"
    environment: sequencer
    secrets:
      DB_CREDENTIALS: arn:aws:secretsmanager:us-east-2:851725450525:secret:rds!cluster-19a608f6-1f4b-4e6a-849f-27831fcf40de-vkcDz2

