environment:
  vault:
    DB_HOST: db-cluster-integration.cluster-cl3xv8fdugsq.us-east-1.rds.amazonaws.com
services:
  api:
    image: 801445322753.dkr.ecr.us-east-1.amazonaws.com/vault
    count: 1
    environment: test
    secrets:
      DB_CREDENTIALS: arn:aws:secretsmanager:us-east-2:851725450525:secret:rds!cluster-32e6d3b7-0fd7-43f6-b108-4648afcf69c1-NgwNkC
