environment:
  api:
    DB_HOST: db-cluster.cluster-cpwwaa4iqa1s.us-east-2.rds.amazonaws.com
    EVM_NETWORK_URL: test-anvil.chainring.co
services:
  api:
    image: 851725450525.dkr.ecr.us-east-2.amazonaws.com/backend
    count: 1
    environment: test
    secrets:
      #DB_CREDENTIALS: arn:aws:secretsmanager:us-east-2:851725450525:secret:rds!cluster-32e6d3b7-0fd7-43f6-b108-4648afcf69c1-NgwNkC
      DB_CREDENTIALS: arn:aws:secretsmanager:us-east-2:851725450525:secret:test/api/copy-of-rds-credentials-fgQFzD
  anvil:
    image: 851725450525.dkr.ecr.us-east-2.amazonaws.com/anvil
    count: 1
    environment: test