name: Restart anvil by cron

on:
  schedule:
    # Run every Sunday at 3:00 AM UTC (11:00 PM NY, 05:00 AM Berlin)
    - cron: '0 3 * * 0'

# make sure it does not interfere with other jobs in progress
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  restart-anvil-and-related-services:
    runs-on: ubuntu-latest
    permissions:
      # needed for aws credentials
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Setup AWS
        uses: ./.github/actions/setup-aws
      - name: Stop and start
        run: |
          cd scripts
          test -d venv || python3 -m venv venv
          . ./venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt
          python3 ecs-deploy.py stop --env demo --services mocker,telegrambot,api,ring
          python3 ecs-deploy.py stop --env demo --services anvil,anvil2
          python3 ecs-deploy.py start --env demo --services anvil,anvil2
          python3 ecs-deploy.py start --env demo --services ring,api,telegrambot,mocker
