name: Build Web UI

on:
  # Manual trigger from the UI
  workflow_dispatch:

  # Call from another workflow (CI)
  workflow_call:


jobs:
  build_frontend:
    name: Web UI build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: ./.github/actions/setup-node-js-20
      - name: Install dependencies
        working-directory: ./web-ui
        run: pnpm install
      - name: Lint
        working-directory: ./web-ui
        run: pnpm run lint
      - name: Typecheck
        working-directory: ./web-ui
        run: pnpm run typecheck
      #      - name: Test
      #        working-directory: ./web-ui
      #        run: pnpm run test --run
      - name: build
        working-directory: ./web-ui
        run: pnpm run build --mode staging