name: Deploy Testnet

on:
  # Manual trigger from the UI
  workflow_dispatch:
    inputs:
      tag:
        description: 'Backend image tag'
        required: true
        type: string

# execute jobs sequentially per branch, needed to keep correct order of deployments
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  build_push_backend:
    name: Build Backend and push to ECR
    permissions:
      id-token: write # needed for aws credentials
      contents: write
      checks: write # for writing test reports
    uses: ./.github/workflows/build-push-backend.yml

  deploy_backend:
    name: Deploy Backend
    needs: [ build_push_backend ]
    permissions:
      id-token: write # needed for aws credentials
      contents: read
    uses: ./.github/workflows/deploy-backend.yml
    with:
      action: upgrade
      environment: testnet
      tag: ${{ needs.build_push_backend.outputs.docker_image_tag }}

  deploy_web_ui:
    name: Deploy Web UI
    needs: [ build_push_backend, deploy_backend ]
    permissions:
      id-token: write # needed for aws credentials
      contents: read
    uses: ./.github/workflows/deploy-web-ui.yml
    with:
      environment: testnet