name: Run integration tests

on:
  # Manual trigger from the UI
  workflow_dispatch:

  # Call from another workflow (CI)
  workflow_call:

concurrency:
  group: 'integration-tests'
  cancel-in-progress: false

jobs:
  integration_tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    permissions:
      # needed for aws credentials
      id-token: write
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: ./.github/actions/setup-java-17
      - name: Setup AWS
        uses: ./.github/actions/setup-aws
      - name: Configure SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CI_BASTION_KEY }}
      - name: Check with Gradle Wrapper
        run: |
          ssh -o StrictHostKeyChecking=no -L 5434:db-cluster.cluster-cpwwaa4iqa1s.us-east-2.rds.amazonaws.com:5432 ec2-user@test-bastion.chainring.co -N &
          sleep 2  # to give the SSH tunnel time to be set up
          DB_PASSWORD=$(aws --region us-east-2 secretsmanager get-secret-value --secret-id 'arn:aws:secretsmanager:us-east-2:851725450525:secret:rds!cluster-32e6d3b7-0fd7-43f6-b108-4648afcf69c1-NgwNkC' | jq -r '.SecretString' | jq -r '.password') \
             ./gradlew check
        env:
          DB_PORT: 5434
          EVM_NETWORK_URL: https://test-anvil.chainring.co
          INTEGRATION_RUN: 1
          API_URL: https://test-api.chainring.co
      - name: Test Report
        uses: dorny/test-reporter@v1.8.0
        if: success() || failure()
        with:
          name: Deployed Integration Tests
          path: '**/build/test-results/test/TEST-*.xml'
          reporter: java-junit
          fail-on-empty: 'false'
      - name: Store Reports
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: deployed-integration-reports
          path: |
            **/build/reports/
            **/build/test-results/